### PR TITLE
Fixed broken symlinks in frameworks

### LINKED ISSUE #818: Symlinks broken in FLAC.Framework for osx
The symlinks for the Resources and Current are broken in the FLAC framework.

This causes a linking fail when building an application using SFML with the error:
>ld: framework not found FLAC

extlibs/libs-osx/Frameworks/FLAC.Framework/Versions/Current
should link to:
extlibs/libs-osx/Frameworks/FLAC.Framework/Versions/A/

extlibs/libs-osx/Frameworks/FLAC.Framework/Resources
should link to:
extlibs/libs-osx/Frameworks/FLAC.Framework/Versions/Current/Resources

### PR DESCRIPTION
**Pull request by mantognini**
Fixes #818.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
@nbollom Can you give this a try?

**Comment by mantognini** [comment]
@eXpl0it3r you're damned too fast, was about to click on "comment" to send the exact same message. :smile:

**Comment by eXpl0it3r** [comment]
Hehe, yeah noticed by the delay of upadting tags, that I might have been too quick. Wasn't really my intention though.

**Comment by nbollom** [comment]
Nope, the symlinks are still broken.

**Comment by mantognini** [comment]
Somehow, git simply refuse to update that file...

**Comment by mantognini** [comment]
Okay, I removed them and add them again, squashed everything and now it should actually work. @nbollom Let me know if that indeed the case for you.

**Comment by nbollom** [comment]
@mantognini Thats fixed it.

Now I have a freetype runtime problem, but that might just be my project structure causing that (sfml as a sub cmake project).

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by mantognini** [comment]
@nbollom If your issue with freetype persists, please open a thread on the forum. ;-)

**Pull request merged**
