### PR TITLE
Remove non-ASCII symbols

### LINKED ISSUE #806: Non-ASCII symbols in Sensor.hpp
There is the symbol `²` [**here**](https://github.com/LaurentGomila/SFML/blob/45810a134505f9d21d58f35f30d05d44c4a3db59/include/SFML/Window/Sensor.hpp#L52), and because of it the file *Sensor.hpp* can't be encoded as ASCII.

The main problem is, this file is for some reason encoded as *latin-1*, which is just a legacy locale-specific encoding that is still used pretty much only on Windows. Even your browser most likely won't display it correctly (if you open the [raw file](https://raw.githubusercontent.com/LaurentGomila/SFML/45810a134505f9d21d58f35f30d05d44c4a3db59/include/SFML/Window/Sensor.hpp))

I noticed this when my code parser choked on CSFML's *Sensor.h*, saying it's not valid UTF-8 (this problem has just been copied to CSFML in [this commit](https://github.com/LaurentGomila/CSFML/commit/fb1824b3b08ff34ec7b863c5937608916dfe5ba4#diff-47220121eccf287e8d46279cefb31a1aR42)). 

This is also broken [in the documentation](http://www.sfml-dev.org/documentation/2.2/classsf_1_1Sensor.php#a687375af3ab77b818fca73735bcaea84), which is supposed to be UTF-8, but actually isn't valid UTF-8.

An obvious fix would be to just change the encoding of this file to *UTF-8*, and that would work better.

(Side note: both *latin-1* and *UTF-8* are supersets of *ASCII*, so one could say every header file right now is encoded as *latin-1*, and every header file except this one is encoded as *ASCII* or *UTF-8*)

But I suggest to just change this to `^2`, because this tiny quirk in just one place is not worth potentially breaking some things that expect ASCII-only.

### PR DESCRIPTION
**Pull request by BlaXpirit**
Fixes #806

### CODE REVIEW

**Comment by BlaXpirit** [comment]
I'm not sure, there may be other non-ASCII symbols here...

**Comment by eXpl0it3r** [comment]
You should also reencode the file as UTF-8 without BOM.

**Comment by BlaXpirit** [comment]
*latin-1* is a superset of *ASCII*. Removing the special characters turns this into ASCII.
*UTF-8* is a superset of *ASCII*. So you could say this file is already in "UTF-8 without BOM". I confirmed this by `git clone -b patch-1 https://github.com/BlaXpirit/SFML`: my text editor shows it as *UTF-8*.

**Comment by eXpl0it3r** [comment]
Can you re-encode [SensorImpl.mm](https://github.com/LaurentGomila/SFML/blob/master/src/SFML/Window/iOS/SensorImpl.mm) as UTF-8 as well and [HIDInputManager.mm](https://github.com/LaurentGomila/SFML/blob/master/src/SFML/Window/OSX/HIDInputManager.mm) (unless @mantognini says one shouldn't)?

**Comment by BlaXpirit** [comment]
I found the following non-ASCII source files:

- examples/cocoa/NSString+stdstring.mm: *UTF-8*  
  position 2111: ©
- src/SFML/Window/OSX/HIDInputManager.mm: *UTF-8*  
  position 31411: §
- src/SFML/Window/OSX/SFApplication.m: *UTF-8*  
  position 3417: ⌘
- src/SFML/Window/OSX/WindowImplCocoa.hpp: *UTF-8*  
  position 3414: ⌘
- src/SFML/Window/OSX/SFWindow.h: *UTF-8*  
  position 2732: ’
- src/SFML/Window/OSX/SFWindow.m: *UTF-8*  
  position 2223: ’
- src/SFML/Window/iOS/SensorImpl.mm  ***latin-1***  
  position 4003: ²

Out of all these I think only the last one needs changing.

**Comment by mantognini** [comment]
OS X related files should already be utf-8 but if it's not the case they could be fixed of course.

**Comment by eXpl0it3r** [comment]
For me `HIDInputManager.mm` seems to not be encoded as UTF-8, but maybe that's just me?

**Comment by eXpl0it3r** [comment]
@BlaXpirit Can you check again the HIDInputManager.mm?

Otherwise, this PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by BlaXpirit** [comment]
So I checked it for the third time. My text editor (Kate) shows HIDInputManager.mm as *UTF-8*.

`chardetect` shows it as *TIS-620*. So I tried to open that file as *TIS-620* and encode as *UTF-8*, which only changed "§" into "ยง", leading me to think that:

- It is not *TIS-620*
- It is *UTF-8*
- The only non-ASCII symbol in it is "§"

**Comment by mantognini** [comment]
If `§` is causing trouble, it could be substituted by `section sign (see Unicode U+00A7)` in the comment on [line 780](https://github.com/LaurentGomila/SFML/blob/master/src/SFML/Window/OSX/HIDInputManager.mm#L780)

**Comment by LaurentGomila** [comment]
I think we should avoid non-ASCII characters whenever possible.

**Comment by binary1248** [comment]
> I think we should avoid non-ASCII characters whenever possible.

:+1:

There really isn't any reason why we should have to use non-ASCII characters in source code. This is C++, and not Java :stuck_out_tongue:.

**Comment by eXpl0it3r** [comment]
© → (C)
§ → see next section
⌘ → Command Key
’ → '
’ → '
² → ^2

**Comment by mantognini** [comment]
:+1:

**Comment by BlaXpirit** [comment]
I've replaced a lot of these characters. Now I can be sure I haven't missed anything:

```bash
export LC_ALL=C
find . -type f -print0 |
while IFS= read -r -d '' file; do
    grep --with-filename --line-number -P '[^ -~\r\n\t]' "$file" |
    grep --invert-match -P '/\.git/' |
    grep --invert-match '/extlibs/' |  # There is a ton of special characters in freetype
    grep --invert-match '^Binary file'
done
```

*src/* is all done.
But I'm not sure how many commits this should be and what to do with these remaining things:

- examples/cocoa/NSString+stdstring.mm:56: `// work for characters like é or à.`
- examples/cocoa/resources/Cocoa-Info.plist:28: `<string>Copyright © [...]</string>`
- examples/cocoa/MainMenu.xib:93: `<string key="NSTitle">Preferences…</string>`
- examples/cocoa/MainMenu.xib:214: `<string key="NSTitle">Open…</string>`
- examples/cocoa/MainMenu.xib:278: `<string key="NSTitle">Save As…</string>`
- examples/cocoa/MainMenu.xib:316: `<string key="NSTitle">Print…</string>`
- examples/cocoa/MainMenu.xib:448: `<string key="NSTitle">Find…</string>`
- examples/cocoa/MainMenu.xib:1232: `<string key="NSTitle">Customize Toolbar…</string>`
- doc/footer.html:5: `Copyright © Laurent Gomila &nbsp;::&nbsp;`
- cmake/Macros.cmake:84: `# [...] user’s frameworks/application bundle`
- readme.txt:15: `Lukas Dürrenberger (eXpl0it3r@sfml-dev.org)`
- tools/xcode/templates/SFML/SFML CLT.xctemplate/main.cpp:11: `// [...]"Edit Scheme…"[...]`
- CMakeLists.txt:230: `# [...] user’s frameworks/application bundle`

**Comment by mantognini** [comment]
Regarding OS X related stuff, it should be alright like that. Two things: xib should not be manually edited -- I don't know how it can break things... --, secondly Xcode is "clever" and will substitute when you type some sequence of characters (`(c)`, `...`, etc.) with their unicode equivalent. So I guess we don't have to fear those too much on that OS.

Regarding the © in footer.html, it could probably be replaced by `&copy;`.

The `’` in Macros.cmake and CMakeLists.txt can be changed to `'`, of course.

**Comment by eXpl0it3r** [comment]
@BlaXpirit Can you update the PR according to @mantognini's comment:

> Regarding the © in footer.html, it could probably be replaced by `&copy;`.

> The `’` in Macros.cmake and CMakeLists.txt can be changed to `'`, of course.

**Comment by eXpl0it3r** [comment]
Feel free to squash the commits, other than that, this PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by mantognini** [comment]
:+1:

**Pull request merged**
