### PR TITLE
Added X11 back to the linker list for FreeBSD

### PR DESCRIPTION
**Pull request by zsbzsb**
It was removed in https://github.com/LaurentGomila/SFML/commit/f464e2502af84ab4a0e8777e32e101812c4e6563. However when I was attempting the [build SFML on FreeBSD with static libs](http://sfml-dev.org:8080/job/sfml-freebsd/621/console) the examples failed to link with the following error.

>/usr/local/bin/ld: ../../lib/libsfml-window-s-d.a(WindowImplX11.cpp.o): undefined reference to symbol 'XCreateIC'
/usr/local/lib/libX11.so.6: error adding symbols: DSO missing from command line

After some digging I discovered ```XCreateIC``` is defined in X11, so when attempting to link the examples to static SFML libs it failed because X11 was not in the linker list.

So this PR adds X11 back to the link list for FreeBSD (and allows linking to static SFML libs again on BSD platforms).

### CODE REVIEW

**Comment by TankOs** [comment]
Looks alright. I'd like to understand why that doesn't happen on Linux, though. Any ideas?

**Comment by binary1248** [comment]
Probably because BSD is trying to be cleaner than Linux and really separating XCB and GLX from Xlib. If you ask me, it's Linux who exhibits the "non-standard" behaviour. If you link to OpenGL on Linux, it automatically pulls in Xlib as well, same with XCB probably. This is why the only real way to get rid of the Xlib dependency is to drop GLX and use EGL like Wayland does (it uses EGL on purpose so it doesn't pull in X) and hope that one day XCB on Linux won't pull in Xlib automatically any more.

**Comment by zsbzsb** [comment]
Well does anyone have anything against this or any suggestions to try instead of linking X11?

**Comment by TankOs** [comment]
@binary1248 
That's true, and that's also what made me wonder why removing the libraries from linkage actually worked... lol

@zsbzsb 
It's alright. I removed it because not necessary on Linux. Now that we know it's necessary, we can simply add them again.

:+1:

**Comment by zsbzsb** [comment]
>we can simply add them again.

:smiley_cat:  :+1:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by binary1248** [comment]
:+1:

**Comment by eXpl0it3r** [comment]
Merged in ae53cfd0d960f6ea9424b63b9141045c1137b7b3

**Pull request closed without merging**
