### PR TITLE
Fixed the paths to the FreeType headers.

### LINKED ISSUE #819: Could NOT find Freetype (missing: FREETYPE_INCLUDE_DIRS)
I get this error when configuring CMake from the latest master checkout.

src/SFML/Graphics/CMakeLists.txt seem to refer to these:

    set(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "${PROJECT_SOURCE_DIR}/extlibs/headers/libfreetype/windows")
    set(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "${PROJECT_SOURCE_DIR}/extlibs/headers/libfreetype/windows/freetype")

But they don't exist.  I can't find a FindFreetype2.cmake file either.

### PR DESCRIPTION
**Pull request by eXpl0it3r**
Fixes #819

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
@fizixx Could you give this a try?

**Comment by fizixx** [comment]
After deleting the CMake cache and configuring from scratch, the exact error was still there.

**Comment by eXpl0it3r** [comment]
What version of CMake are you using?
Does `FindFreetype.cmake` exist in `C:\Program Files (x86)\CMake\share\cmake-3.2\Modules`?

**Comment by fizixx** [comment]
I was using CMake 2.8.12.2 which does include the FindFreetype.cmake file.

I switched to using 3.2.0-rc2 just now and regenerated everything and it works fine.

So it seems CMake 2.8 is not supported any more?

**Comment by eXpl0it3r** [comment]
Interesting. My guess is, that the FindFreetype.cmake shipped with CMake 2.8 was made for the older FreeType2 version. Their header structure changed and thus it won't "find" FreeType2 anymore.

I guess we're left with two options:

* Ship our own FindFreetype.cmake
* Change the `cmake_minimum_required` version number.

**Comment by MarioLiebisch** [comment]
Hm... this is tricky, but I'd rather vote for pushing the CMake version to 2.9 rather than duplicating code. A bundled CMake script wouldn't work with different versions either, so you're just moving the issue either way.

**Comment by eXpl0it3r** [comment]
Does CMake 2.9 contain the new FindFreetype.cmake?

**Comment by MarioLiebisch** [comment]
Didn't actually check. Replace "2.9" with "whatever version fixes it", unless it's too new?

**Comment by eXpl0it3r** [comment]
2.9 [doesn't even exist](http://www.cmake.org/files/). :wink:

**Comment by fizixx** [comment]
Here is the change log for the FindFreetype.cmake file in CMake if that helps at all.  I don't really know how the find_package stuff works internally.

http://www.cmake.org/gitweb?p=cmake.git;a=history;f=Modules/FindFreetype.cmake;h=7d46d1563f9c84edf54cee12b234d16fab612107;hb=HEAD

**Comment by eXpl0it3r** [comment]
Since changing the minimum required CMake version would cause issues for Ubuntu and Debian users, I instead added the FindFreetype.cmake module which should work find with the old and the new FreeType2 paths.

**Comment by MarioLiebisch** [comment]
Haven't had a look, but the new FindFreetype.cmake will find old and new versions?

**Comment by eXpl0it3r** [comment]
It has the [new and the old path](https://github.com/LaurentGomila/SFML/pull/820/files#diff-21bf7456a1f010352c0f1a1860631ff7R68).

**Comment by eXpl0it3r** [comment]
Trying out CMake 2.8 on Windows, it seems like the current source code (including the 2.2 tag) uses cmake_parse_arguments() which isn't part of CMake 2.8. So if we wanted to be compatible, we'd have to ship that file as well.

Plus I had to slightly modify the FindFreetype.cmake file.

**Comment by eXpl0it3r** [comment]
Looks like the missing file was added in CMake 2.8.3, so that version is fine for Debian and alike. I've simply changed the minimum required version to 2.8.3 instead of 2.8.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
