### PR TITLE
Fixed Window::getPosition() which was took the border into account twice...

### PR DESCRIPTION
**Pull request by gfannes**
... (for manjaro linux at least).
I have no other unix variant, so I cannot test how universal the fix is.

### CODE REVIEW

**Comment by binary1248** [comment]
Is this still something we want? The original PR was based off the old Xlib implementation, so I can rewrite that part using XCB, but @mantognini will still have to fill this code snippet out for me. :grin:

```objc++
Vector2i WindowImplCocoa::getClientAreaPosition() const
{
    // magic stuff here
}
```

**Comment by LaurentGomila** [comment]
No, I've quickly re-read the discussion and I understand correctly we agreed to forget about this new function.

**Comment by mantognini** [comment]
I agree.

**Comment by binary1248** [comment]
OK...

As for the mentioned secondary issues:
* fix the issue with getPosition() for linux: setPosition(getPosition()) should not move the window.

This has been fixed in master since the XCB rewrite. The window is positioned at (0,0) when it is at the top left corner of the screen and setting its position to a new value also asserts that the value returned by getPosition() after that is equal to the set value.

* clarify the comments for getPosition(): I guess that its intended meaning is to give the position of the top-left _including_ title and border.

My guess is that this was intended as an alternative "solution" to the problem. If it wasn't, then this definition can be considered more confusing than just simply saying "Get the position of the window." since people already understand that the position of the window is where the top left corner of the window (including all its decorations) is located on the screen.

I'm closing this issue for now. Feel free to provide more information if you feel this is worth picking up again in the future.

**Pull request closed without merging**
