### PR TITLE
Moved stb_image into the extlibs directory.

### PR DESCRIPTION
**Pull request by binary1248**
Title says it all. :grin:

### CODE REVIEW

**Comment by LaurentGomila** [comment]
Can't we have

 ```cpp
#include <stb_image/stb_image.h>
#include <stb_image/stb_image_write.h>
```

... so that we avoid an extra include path for it, and it follows the implicit convention of <library/header> includes (which avoids conflicts in case of headers named the same way, such as config.h).

**Comment by binary1248** [comment]
The other libraries are also handled like that. Look at the jpeg headers right underneath them.

**Comment by LaurentGomila** [comment]
Hmm ok, whatever.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
