### PR TITLE
Removed XCB dependencies

### PR DESCRIPTION
**Pull request by binary1248**
Got rid of EWMH, ICCCM, Keysyms and Util XCB dependencies. It might even build on Ubuntu 12.04 again, since the "class bug" inside ICCCM is no longer an issue and crashes can't happen because of EWMH. Also added missing XCB libraries to FindSFML.cmake.

Tested fully static linking using the new FindSFML.cmake in SFGUI, works for me.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Would be great if some of our Linuxy people could test this.

**Comment by binary1248** [comment]
Replaced std::memset with std::fill in Display.hpp.

**Comment by binary1248** [comment]
Replaced `<X11/Xlib-xcb.h>` with `<xcb/xcb.h>` in InputImpl.cpp since Xlib is no longer used in it.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by zsbzsb** [comment]
Confirmed that is builds fine on FreeBSD :+1:

**Comment by binary1248** [comment]
Fixed fullscreen not working properly when using Unity.

http://en.sfml-dev.org/forums/index.php?topic=17845.0

**Pull request merged**
