### PR TITLE
Switched to the stdio FILE* API for handling streams to provide the expected behavior to Vorbis.

### LINKED ISSUE #845: Audio module fails to open one paged ogg/vorbis audio files
Description and test files: http://en.sfml-dev.org/forums/index.php?topic=17788.0

The problem is in ```FileInputStream```: once the internal file has reached its end, it is in fail/eof state and all its functions return junk. Clearing the error bits at the beginning of ```FileInputStream::getSize```(the one that makes the ogg/vorbis reader fail) makes the FLAC reader enter an infinite loop for some reason.

I'm about to switch the implementation to the good old FILE* API. Unless someone finds a clean way to handle this stuff :grin:

### PR DESCRIPTION
**Pull request by eXpl0it3r**
Fixes #845

### CODE REVIEW

**Comment by LaurentGomila** [comment]
Have you tested it with all other kind of resources and formats?

**Comment by binary1248** [comment]
:+1: Works for me.

> Have you tested it with all other kind of resources and formats?

What other kind of resources and formats? The newest sound example already plays wav, ogg and flac files... The problematic sound files provided on the the forum also work with this fix.

**Comment by LaurentGomila** [comment]
> What other kind of resources and formats?

sf::Image, sf::SoundBuffer (the backend is the same but used differently).

**Comment by binary1248** [comment]
sf::Image uses stb_image, and not sf::FileInputStream.

sf::SoundBuffer is already indirectly tested in the sound example since sf::Sound makes use of it.

**Comment by LaurentGomila** [comment]
> sf::Image uses stb_image, and not sf::FileInputStream.

I mean ```sf::Image::loadFromStream(sf::FileInputStream)```. All resource classes that use streams use them differently, if we provide official input streams we should make sure that they at least work with all of our classes.

**Comment by eXpl0it3r** [comment]
I have not, since I changed and pushed it a few minutes before going to bed. :wink:

**Comment by eXpl0it3r** [comment]
Not directly related, but shouldn't `System.hpp` also include `FileInputStream.hpp` and `MemoryInputStream.hpp`?

**Comment by eXpl0it3r** [comment]
Not sure how much I've missed, but this seems to work fine so far.

```cpp
#include <SFML/Audio.hpp>
#include <SFML/Graphics.hpp>
#include <SFML/System/FileInputStream.hpp>

int main()
{
	sf::RenderWindow window{{1024, 768}, "Test"};

	sf::FileInputStream font_stream;
	font_stream.open("arial.ttf");

	sf::Font font;
	font.loadFromStream(font_stream);

	sf::Text text("Hello World", font, 50);

	sf::FileInputStream image_stream1;
	image_stream1.open("image.png");

	sf::Texture texture1;
	texture1.loadFromStream(image_stream1);

	sf::Sprite sprite1(texture1);

	sf::FileInputStream image_stream2;
	image_stream2.open("image.jpg");

	sf::Texture texture2;
	texture2.loadFromStream(image_stream2);

	sf::Sprite sprite2(texture2);

	sf::FileInputStream shader_stream;
	shader_stream.open("wave.vert");

	sf::Shader shader;
	shader.loadFromStream(shader_stream, sf::Shader::Vertex);

	sf::FileInputStream sound_stream;
	sound_stream.open("music.flac");

	sf::SoundBuffer soundbuffer;
	soundbuffer.loadFromStream(sound_stream);

	sf::Sound sound(soundbuffer);
	sound.play();

	while(window.isOpen())
	{
		sf::Event event;
		while(window.pollEvent(event))
		{
			if(event.type == sf::Event::Closed)
				window.close();
			else if(event.type == sf::Event::MouseMoved)
			{
				shader.setParameter("wave_phase", 10);
				shader.setParameter("wave_amplitude", event.mouseMove.x * 40, event.mouseMove.y * 40);
			}
		}

		window.clear();
		window.draw(text);
		window.draw(sprite1, &shader);
		window.draw(sprite2);
		window.display();
	}
}
```

**Comment by LaurentGomila** [comment]
:+1:

> shouldn't System.hpp also include FileInputStream.hpp and MemoryInputStream.hpp?

Absolutely.

**Comment by eXpl0it3r** [comment]
>> shouldn't System.hpp also include FileInputStream.hpp and MemoryInputStream.hpp?
> Absolutely.

I'll make another PR on this, since it's also missing `Time.hpp` and I'll recheck the other headers.

**Comment by eXpl0it3r** [comment]
If you think my test was sufficient please change the label from undecided to accepted.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
