### PR TITLE
Only link sfml-main for the GUI examples in release mode.

### LINKED ISSUE #610: Don't link sfml-main to GUI examples
Time and again, people post on the SFGUI forum and the SFML forum regarding "stuff that doesn't work" or some corrupted graphics etc. When I ask them if their drivers/system is set up properly, they tend to say "the SFML examples work fine" and assume that everything is good. When I tell them to enable the console they find out that SFML has been spamming them with OpenGL errors and what not but they just didn't have the console enabled to see them. Had they seen those errors when running the examples to begin with, I think they would have fixed what was wrong with their system before assuming that something is wrong with the libraries.

Is it a good idea to make the examples display a console in the background? It would be easier and faster for people to diagnose problems that way before starting their own project with a broken environment.

I initially thought about only enabling the console subsystem for the debug build of the examples but CMake doesn't allow setting WIN32_EXECUTABLE based on build-type in multi-configuration mode and the only workaround has been broken for the last 2 years, [see here](http://public.kitware.com/Bug/view.php?id=12566). So if we went ahead and did this, it is all or nothing.

### PR DESCRIPTION
**Pull request by eXpl0it3r**
Fixes #610

### CODE REVIEW

**Comment by LaurentGomila** [comment]
This won't work for multi-configuration CMake generators (Visual Studio, ...), where ```${CMAKE_BUILD_TYPE}``` is irrelevant.

**Comment by eXpl0it3r** [comment]
True, so should it not link against sfml-main in every case?

**Comment by LaurentGomila** [comment]
That, or we apply this PR anyway:
* for official SFML releases we only use makefile generators, so this issue doesn't apply for us
* for user builds, multi-configuration generators will produce examples with a console even in release build, is it a problem?

If we apply the PR as it is, we should at least add a comment such as *"won't be applied in multi-configuration generators such as Visual Studio, but we don't care"*.

**Comment by eXpl0it3r** [comment]
> for user builds, multi-configuration generators will produce examples with a console even in release build, is it a problem?

Since it's using `NOT xyz STREQUAL "Release"` it will link against sfml-main with multi-configuration generators.
While thinking about it, I also noticed that in debug we theoretically would had to link `sfml-main-d`.

**Comment by MarioLiebisch** [comment]
I'm quite sure CMake introduced something to fix that long standing issue with `CMAKE_BUILD_TYPE`, just not sure which version. I think with 3.0...

**Comment by LaurentGomila** [comment]
Are thinking of [Generator expressions](http://www.cmake.org/cmake/help/v3.1/manual/cmake-generator-expressions.7.html)? I don't think they can solve this particular issue.

**Comment by MarioLiebisch** [comment]
Not sure, I thought it's something differen,t but can't find anything related. Those might be able to solve this though.

**Comment by eXpl0it3r** [comment]
Just noticed that I saw things wrong, because besides `CMAKE_BUILD_TYPE` there's also the `CMAKE_CONFIGURATION_TYPES`.

The current issue I have with Visual Studio though is, that the win32 example uses `WinMain` as entry point, but we don't set the subsystem to Window. How would we go about fixing this?

**Comment by LaurentGomila** [comment]
The single argument that is not ignores, ```HINSTANCE instance```, can be retrieved with a call to ```GetModuleHandle(NULL)```. So we can safely replace ```WinMain``` by ```main```.

**Comment by eXpl0it3r** [comment]
Since it's a Windows example, do we really want to go with `main()` and `GetModuleHandle(NULL)`?

**Comment by LaurentGomila** [comment]
If you don't want to use the ```WIN32``` CMake flag, but yet use ```WinMain``` as the entry point, you'll have to set compiler specific linker settings. Do you really want that?

**Comment by binary1248** [comment]
Wouldn't just using
```cmake
target_link_libraries(${target} optimized sfml-main)
```
work?

**Comment by eXpl0it3r** [comment]
@binary1248 The line above the linking would also need to be applied only for the optimized target (i.e. `WIN32`).

I've updated the PR and it now only removes the console window if there are no multiple configuration types and it's built in release mode.

Additionally the win32 example has been updated.

**Comment by binary1248** [comment]
Well... yeah... I didn't say that it would solve the WIN32 issue as well. There will have to be another solution for that.

**Comment by eXpl0it3r** [comment]
An further comments on this?

**Comment by MarioLiebisch** [comment]
I'd tend to split the examples completely, i.e. provide a standalone CMakeLists.txt for them (would act as another part of the example) and exclude them from building the libraries themselves.

**Comment by eXpl0it3r** [comment]
That's what #800 is for or any other PR, this is about linking sfml-main, so let's focus on that.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
