### PR TITLE
Fixed the issue where trying to open a stream didin't reset the stream first.

### LINKED ISSUE #822: sf::Music::openFromStream and sf::SoundBuffer::loadFromStream fails for non-flac files
Loading Music or SoundBuffer through an InputStream fails, but loading straight from the file with openFromFile/loadFromFile succeeds.

Code which recreates (orchestral.ogg from examples)
```cpp
#include <SFML/Audio.hpp>
#include <SFML/System/FileInputStream.hpp>
#include <iostream>

int main() {
    std::cout << "Starting..." << std::endl;
    sf::Music fileMusic;
    if (!fileMusic.openFromFile("orchestral.ogg")) {
        std::cerr << "Too early boom?"  << std::endl;
        return 3;
    }

    sf::FileInputStream stream;
    sf::Music music;
    if (!stream.open("orchestral.ogg")) {
        std::cerr << "Too early boom?"  << std::endl;
        return 2;
    }
    if (!music.openFromStream(stream)) {
        std::cerr << "BOOM!"  << std::endl;
        return 1;
    }
    std::cout << "Done" << std::endl;
    return 0;
}
```

### PR DESCRIPTION
**Pull request by eXpl0it3r**
Fixes #822.
Discussion can be found [here](http://en.sfml-dev.org/forums/index.php?topic=17692.msg127208#msg127208).

### CODE REVIEW

**Comment by LaurentGomila** [comment]
:+1:

**Comment by binary1248** [comment]
:+1:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by zsbzsb** [comment]
You have a typo in the commit message (and issue title) :wink:

**Comment by eXpl0it3r** [comment]
Hehe, thanks for mentioning it.

**Pull request merged**
