### PR TITLE
Changed the SOVERSION to major.minor.

### PR DESCRIPTION
**Pull request by eXpl0it3r**
Here are is the change as discussed.

### CODE REVIEW

**Comment by binary1248** [comment]
:+1:

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
Since on Linux the shared libraries use `-major.minor.so` as suffix, I was wondering if we should apply the same naming for Windows DLLs as well, i.e. `-major.minor.dll`?

**Comment by zsbzsb** [comment]
I would agree with that change to the dll naming convention.

**Comment by MarioLiebisch** [comment]
> I was wondering if we should apply the same naming for Windows DLLs as well

Not sure about that. Doing that is very, very uncommon. Especially considering that Windows will always try to load dependencies straight from the executable's own folder.

Also don't forget STL incompatibilities between toolchains and their versions. Just because you've got the same version DLL doesn't mean it's really compatible.

**Comment by zsbzsb** [comment]
>Also don't forget STL incompatibilities between toolchains and their versions. Just because you've got the same version DLL doesn't mean it's really compatible.

Well... this is already the situation. You can't do much at all to fix this.

**Comment by MarioLiebisch** [comment]
Correct. So I'd just stick with the current approach and leave the Windows file names as-is.

**Comment by eXpl0it3r** [comment]
Any more comments on this (-2.2.dll vs -2.dll)?

**Comment by binary1248** [comment]
DLL hell is bad enough. I guess if we can prevent the dynamic linker from loading an incompatible (or simply the wrong) library, it wouldn't harm. -2.2.dll reveals the ABI version the best without having to resort to more elaborate methods.

**Comment by zsbzsb** [comment]
I saw that DLLs should have the major and minor, but also think we should save that discussion for another time if it stalls this PR.

**Comment by eXpl0it3r** [comment]
Given the other open issues, we're not in a hurry with the change. So I'm still interested in further comments.

**Comment by eXpl0it3r** [comment]
Added the change for the DLLs, but I'm still open to comments about.

**Comment by zsbzsb** [comment]
This is about all I can think of regarding the change to dll naming.

*Pros*
- More information available about version of SFML (useful when solving linker errors, missing symbols [time division anyone?] determining installed version, ect)
- Can help solve some side affects of DLL hell as it can prevent older versions of SFML being loaded that don't match if the required version is not present
- MS even adds versions to their DLLs - msvcp[60|100|110|120].dll
- Can be added to CSFML and also help out bindings so when they dynamically load SFML they will load the right version.

*Cons*
- Maybe breaks some existing install/packaging scripts
- Changing how it currently is
- Is there anything else?

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
With this PR, we'll only change the soversion. The DLL stuff will be discussed elsewhere.

**Pull request merged**
