### PR TITLE
Bugfix/541 osx openal threadsafety

### PR DESCRIPTION
**Pull request by Ceylo**
Provides OpenAL-soft 1.16 instead of OS X's OpenAL which is buggy.

### CODE REVIEW

**Comment by binary1248** [comment]
Are 7 commits really necessary to change 6 files? :grin:

https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one

Then push using a force push (only do it for this purpose, none other!).

**Comment by mantognini** [comment]
Actually, I forgot about the templates... Could you change [those two lines](https://github.com/LaurentGomila/SFML/blob/master/tools/xcode/templates/SFML/SFML%20App.xctemplate/TemplateInfo.plist.in#L231-L232) by the following and remove [this comment](https://github.com/LaurentGomila/SFML/blob/master/tools/xcode/templates/SFML/SFML%20App.xctemplate/TemplateInfo.plist.in#L238)?

```
            for f in "FLAC" "ogg" "vorbis" "vorbisenc" "vorbisfile" "OpenAL"
```

Thanks :-)

Beside that, this works great! So once this extra change is committed and everything is squashed it's all good for merge.

**Comment by Ceylo** [comment]
Hmm ok. However what is the link between this pull request and the comment you want me to remove?

**Comment by mantognini** [comment]
Oh, they are simply useless; the next statements are really obvious so... Two birds with one stone. :)

**Comment by Ceylo** [comment]
I hope I didn't forget anything now :D

**Comment by mantognini** [comment]
I was thinking of removing both comments but that's really not important and since it works well for me, let's move on and merge it! :-)

**Comment by robertmassaioli** [comment]
So this is hitting me too on OSX. This issue has been going on for a while. I'm experiencing it too. I can also confirm that simply trying to open one file with SFML results in a crash every single time I run my program:

    * thread #6: tid = 0x0005, 0x000000010497808d OpenAL`OALSource::RemoveBuffersFromQueue(unsigned int, unsigned int*) + 473, stop reason = signal SIGSTOP
      * frame #0: 0x000000010497808d OpenAL`OALSource::RemoveBuffersFromQueue(unsigned int, unsigned int*) + 473
        frame #1: 0x000000010496c77d OpenAL`alSourceUnqueueBuffers + 441
        frame #2: 0x0000000104934cb9 libsfml-audio.2.2.0.dylib`sf::SoundStream::clearQueue() + 109
        frame #3: 0x0000000104934298 libsfml-audio.2.2.0.dylib`sf::SoundStream::streamData() + 1260
        frame #4: 0x000000010495acae libsfml-system.2.2.0.dylib`sf::priv::ThreadImpl::entryPoint(void*) + 26
        frame #5: 0x00007fff8aeea899 libsystem_pthread.dylib`_pthread_body + 138
        frame #6: 0x00007fff8aeea72a libsystem_pthread.dylib`_pthread_start + 137
        frame #7: 0x00007fff8aeeefc9 libsystem_pthread.dylib`thread_start + 13

The original issue (https://github.com/LaurentGomila/SFML/issues/541) was from March 2 last year, meaning that this issue has been going on now for about one year and one month. Would be great if we could fix this. Would really help with an app that I am writing that I hope to have depend on SFML.

In the meantime I'm going to try my code out on Linux just to make sure that this issue is OSX specific. Also, I'll try and check out this branch and see if it works on OSX.

**Comment by robertmassaioli** [comment]
Okay, after installing this branch on my OSX machine and compiling it into my code sf::Music::openFromFile always returns false on my WAV files. I'm not sure if this is a legitimate problem that I was not aware of with SFML 2.2 because of the other OpenAL issues. But I thought that you should be aware of what I was experiencing so that you could test it out too.

I'll try to dig further; if I find anything further I'll drop it here.

**Comment by robertmassaioli** [comment]
Oh yeah, to build your code:

    cd /path/to/your/branch/checkout
    mkdir localbuild && cd localbuild
    cmake ..
    make
    make install

Then I pointed my code to that build of SFML. If I missed a build step then just let me know; that would explain why the audio files are not loading. Cheers.

**Comment by robertmassaioli** [comment]
However examples/sound works on my machine using your checkout. So I must be doing something wrong. :)

**Comment by robertmassaioli** [comment]
Okay, I am actually generating the WAV files in advance (as part of my build process) that need to be played by SFML later. I am using libsndfile to generate those files and the format that I was using was: SF_FORMAT_WAV | SF_FORMAT_PCM_32. However, it turns out that any WAV files with 32 bits of data will fail to be play correctly. I had to change the format to SF_FORMAT_WAV | SF_FORMAT_PCM_16 and now it works great with this branch!

You can find the [WAV file with 32 bits per sample here][1]. I'll go make another issue about this instead of polluting this further.

 [1]: https://s3.amazonaws.com/uploads.hipchat.com/10804/83693/0faMzNh4zU8d09A/out-1.wav

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by robertmassaioli** [comment]
After more testing this branch makes my code work on OSX. It has a bug thumbs up from me.

**Comment by eXpl0it3r** [comment]
Merged in ce16554763177d7285248e81e9b0e0201f0c43e3

**Comment by robertmassaioli** [comment]
This is excellent, when is the next release planned for? OSX users could really use this fix.

**Comment by zsbzsb** [comment]
>when is the next release planned for?

When the [2.3 milestone](https://github.com/LaurentGomila/SFML/milestones/2.3) is complete.

**Comment by mantognini** [comment]
@DomT4, if you plan to update brew formula for SFML 2.3, you might want to be aware of this. ;-)

**Comment by zackthehuman** [comment]
Hi. I'm still experiencing the issue described in #541, which I reference in a bug for my project (hakase-labs/hikari#233). I'm building SFML 2.3 from source, but I also tried 2.2 and 2.1. Should it be possible to experience the same threading-related crash even with 2.3?

**Comment by mantognini** [comment]
> Should it be possible to experience the same threading-related crash even with 2.3?

Probably not. Make sure you don't have old binaries/headers still on your system when you clean build your app.

If it's still happen, let me know.

**Pull request closed without merging**
