### PR TITLE
Updated FreeType to version 2.5.5.

### LINKED ISSUE #799: Update the precompiled FreeType library
The current version shipped with SFML is 2.4.4, the latest stable version is 2.5.5.

Benefits of updating:

* starting at version 2.5.3, FreeType can be configured to use Harfbuzz for better text layout (see #246)
* it now comes with CMake files so it's much easier to build
* quality is better

### PR DESCRIPTION
**Pull request by eXpl0it3r**
Fixes #799

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
So what about iOS? :smile:

**Comment by eXpl0it3r** [comment]
@BlueCobold / @mantognini / @LaurentGomila can someone provide iOS libs?

**Comment by mantognini** [comment]
Probably not this week. :-/

**Comment by BlueCobold** [comment]
I can tomorrow.

**Comment by BlueCobold** [comment]
@eXpl0it3r I've sent you the build iOS lib via IRC this morning

**Comment by eXpl0it3r** [comment]
The iOS lib has been added as well. Anything left to do besides further testing?

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
