### PR TITLE
Replace Xlib by XCB (#200)

### PR DESCRIPTION
**Pull request by TankOs**
This pull request replaces the use of Xlib by XCB, a more modern library for working with X11.

Most work has been done by @Lukas-W. I fixed some issues and adjusted the X11 example. Commits have been squelched.

### CODE REVIEW

**Comment by TankOs** [comment]
@Mischa-Alff 
Just tested, it works. However, I will have to adjust the window focus code to use XCB to be fully compatible. We knew that this is going to happen, because XCB wasn't accepted for 2.2. :cat2:

@jcowgill 
Thank you, I fixed some more spots. However, I'm not quite sure about the warning level anyway. I usually compile with -Wall -Wextra -Wshadow -Wconversion -pedantic, and that spits out tons of warnings. At least the "commonly used" triggers are quiet now. ;-)

@LaurentGomila 
Thanks. The proper line was dropped as it wasn't even used.

**Comment by eXpl0it3r** [comment]
> Just tested, it works. However, I will have to adjust the window focus code to use XCB to be fully compatible.

Do you want to do this before or after merging this branch?

**Comment by TankOs** [comment]
@eXpl0it3r Before, of course. Otherwise the XCB support is not complete.

**Comment by TankOs** [comment]
I'm done. This needs heavy testing, please merge. :+1: :cat2:

**Comment by eXpl0it3r** [comment]
This PR has been added again to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by TankOs** [comment]
:cat2:

**Comment by Lukas-W** [comment]
:bike:

**Pull request merged**
