### PR TITLE
Added missing includes in the general headers.

### PR DESCRIPTION
**Pull request by eXpl0it3r**
I'm not sure what the properties are to include a header, thus I'll just list what isn't included and we can decide if it should get added. Also should we sort the headers lexicographical or "group" them?

*System*

* `NonCopyable.hpp`

*Window*

* `GlResource.hpp`
* `WindowHandle.hpp`

*Graphics*

* `Drawable.hpp`
* `PrimitiveType.hpp`
* `Rect.hpp`
* `RenderTarget.hpp`
* `Transformable.hpp`

*Audio*

* `AlResource.hpp`
* `SoundSource.hpp`

*Network*

* `Socket.hpp`
* `SocketHandle.hpp`

### CODE REVIEW

**Comment by Bromeon** [comment]
In my opinion, all headers in the public API should be included from the module headers. That is, not those for dependencies or symbols in `sf::priv` namespace. It's also not a reason to not include a certain header just because it is indirectly included by another one -- that's an implementation detail.

Lexicographical sorting makes sense... Grouping is probably a bit arbitrary :)

**Comment by eXpl0it3r** [comment]
So should I add everything?

Personally I'd be fine not to include `AlResource.hpp` and `GlResource.hpp` since I don't think they could be used (easily) for anything else than how we use it internally.

**Comment by Bromeon** [comment]
You're right. I think the problem is that both classes are currently in the public API although they shouldn't be. Even the documentation of `GlResource` says "This class is for internal use only". I'd suggest we adapt the documentation or move both to namespace `sf::priv` (in a different PR).

(It doesn't really matter functionality-wise because they're indirectly included as base classes, but we should be consistent with the includes)

**Comment by binary1248** [comment]
We don't even have to do that. sf::priv is still a publicly accessible namespace. If you really wanted to get GlResource out of there, just add it as a member pointer in all the classes that derive from it now and forward declare it or store it as a `void*`. Deriving from it isn't even necessary since it doesn't contain _any_ non-static members anyway.

Maybe I might submit a PR doing just this (the same for AlResource), it seems logical and benefits everybody.

**Comment by Bromeon** [comment]
> sf::priv is still a publicly accessible namespace

Yes, but it's explicitly marked as private and not documented. Which implies that we can change anything inside it at any time, and nobody has the right to complain :P

> Deriving from it isn't even necessary since it doesn't contain any non-static members anyway.

That's not completely true -- the idea is that default constructor and destructor are invoked automatically, and before/after any members. You would have to do all of that manually with member pointers -- and considering that there is no real advantage, I don't think that's a good idea. We don't even safe compile time because the headers are self-contained and tiny.

**Comment by binary1248** [comment]
I don't know what the guideline is behind the `sf::priv::` namespace, but doing a text search in the public headers yields that it is only used in forward declarations of `m_impl` types. @LaurentGomila and @mantognini, can you shed some light on the `sf::priv::` namespace and how it was intended to be used?

**Comment by eXpl0it3r** [comment]
Added the other headers. Feel free to say if something needs to be changed or set the "accepted" flag otherwise. :wink:

**Comment by LaurentGomila** [comment]
If you don't know how to handle the ```sf::priv``` namespace, and there's no particular issue with it, I'd say... don't change anything. About the original question, I'm not strict about it but my feeling is that private headers should not appear in module headers, although they are part of the distributed SFML headers. Only end-user classes should appear there.

**Comment by eXpl0it3r** [comment]
> I'm not strict about it but my feeling is that private headers should not appear in module headers

That's one of the issues I have. Which ones *are* private headers?

**Comment by Bromeon** [comment]
And why are private headers still documented? :stuck_out_tongue:

In Thor, I created sub-directories called "Detail" for private headers. They also contain .inl files for templates. I told Doxygen to exclude those directories, so the headers won't appear in the public API documentation.

**Comment by LaurentGomila** [comment]
> That's one of the issues I have. Which ones are private headers?

I thought we were talking about ```sf::priv```, but ```GlResource``` is not in this namespace. Well, then we're talking about stuff which is marked as internal :grin:

> And why are private headers still documented?

Documentation is not only for end users.

**Comment by eXpl0it3r** [comment]
Well I still don't know what the general stance on this PR is, but I guess I'll just add my usual sentence then.

This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by binary1248** [comment]
Let's put it this way: People (both us and the users) aren't going to lose any sleep over whether GlResource and AlResource are part of those headers or in `sf::priv::` or not, so whichever you choose, it really doesn't matter that much. We have more important issues to worry about. :wink:

**Pull request merged**
