### PR TITLE
Added support for clipping masks (Implements #1)

### PR DESCRIPTION
**Pull request by zsbzsb**
This is ready for a code review, hoping for a SFML 2.4 inclusion. This implements #1, yes the very first issue. :smile:

I based my branch on /feature/gl_dev_new due to the OpenGL changes. Clipping is done with the stencil buffer which gets enabled when a mask is applied to the render states.

Some points from #1 are answered below about this implementation.

>And do we clip in scene coordinates or in window coordinates?

Clipping is done in scene coordinates.

>However since it can be disabled (and is currently not enabled by default) in the context settings.

It is now enabled by default in the context and render texture constructors.

>it implies that the user can disable clipping masks, without even knowing it. So this must be at least well documented, and even enforced if possible.

It is now noted in the documentation that disabling stencil buffer will disable clipping masks. As for enforcing it? Its not really needed, if the user disables it - it is their fault because it is clearly stated.

>So the main problem is to decide what we use to define the clipping area. We could start with a ```const sf::Drawable*``` to have maximum flexibility.

Clipping area is defined by the ```sf::ClippingMask``` class which is a container for multiple ```const sf::Drawable*``` pointers.

>Another question is: do we allow only one active mask, or do we provide the ability to add multiple masks?

Only 1 mask is active at one time, but it can be defined by multiple drawables.

As with my other PR (#840), please review and test and then give feedback. Even textures with alpha channels are supported.

Code below will work with [this commit](https://github.com/zsbzsb/SFML/commit/7f5512ff6730d2f6b6a2f2265723aeb955114291).

```
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window({ 800, 600 }, "Clipping Mask Test");
    window.setVerticalSyncEnabled(true);

    // create a circle for part of the clipping mask
    sf::CircleShape keyholetop(50);
    keyholetop.setOrigin({ 50, 50 });

    // create a square for part of the clipping mask
    sf::RectangleShape keyholebody({ 36, 150 });
    keyholebody.setOrigin({ 18, 0 });

    // create the clipping mask
    sf::ClippingMask clipmask;

    // add the shapes to the clipping mask
    // sf::ClippingMask behaves like sf::VertexArray
    // so you can append any sf::Drawable to the mask
    // the mask will not copy the sf::Drawable, it only stores a pointer
    clipmask.append(keyholetop);
    clipmask.append(keyholebody);

    sf::Texture background;
    // use any background image
    // I used the image from opengl example
    background.loadFromFile("background.jpg");

    sf::Sprite backgroundsprite(background);

    // create a render states and assign the clip mask
    sf::RenderStates states = sf::RenderStates::Default;
    states.mask = &clipmask;

    while (window.isOpen())
    {
        sf::Event e;
        while (window.pollEvent(e))
        {
            if (e.type == sf::Event::Closed)
                window.close();
        }

        sf::Vector2f mousepos = window.mapPixelToCoords(sf::Mouse::getPosition(window));

        keyholetop.setPosition(mousepos);
        keyholebody.setPosition(mousepos);

        window.clear(sf::Color::Blue);

        window.draw(backgroundsprite, states);

        window.display();
    }
}
```

Example Screenshot

### CODE REVIEW

**Comment by LaurentGomila** [comment]
This is awesome, but as you may imagine, there will be a long discussion before this PR is possibly accepted ;)

The first annoying thing that I see is that you cannot draw a whole scene with a mask. With your implementation, you'll clear & fill the stencil buffer with the same content for *every* drawable of the scene, instead of just once. I guess we need to choose between a simple and well-integrated API, and a more verbose but more flexible one.

Another thing is that the ```ClippingMask``` class is just a limited ```std::vector``` with a transform (which shouldn't be public by the way -- I'd rather make the class inherit from ```sf::Transformable```). Maybe we should think of a smarter public API for it. Especially for removing drawables, which is required for a very common use case: pushing/popping clipping rectangles, as with a GUI.

And finally, I'm worried about stencil buffer support, especially with crappy drivers (Intel, Linux, ...).

**Comment by zsbzsb** [comment]
>there will be a long discussion before this PR is possibly accepted

Oh, of course... there can't be any other way :tongue:

May I suggest however, lets focus on implementing it and not getting too nit picky :cat2: 

>With your implementation, you'll clear & fill the stencil buffer with the same content for every drawable of the scene,

I thought about caching the stencil buffer, but I decided for the simple implementation instead of the complicated one. I will work on caching the buffer so we don't need to redraw it every time. The difficult part will be determining if any of the drawables have changed since the last time we drew the mask.

> Maybe we should think of a smarter public API for it.

Just thinking here.... maybe instead of adding the clipping mask as part of the render states, we could make it like the view. With ```sf::RenderWindow::[set|get|clear]ClippingMask()``` so whenever the user changes the mask they must explicitly register it with the window.

>with a transform (which shouldn't be public by the way -- I'd rather make the class inherit from ```sf::Transformable```)

I added the transform last minute (it wasn't in the first commit), I wanted a way to be able to transform the entire mask when drawing it to the stencil buffer so I added a public transform (like in render states). But I guess we could also inherit from ```sf::Transformable``` as that would make more sense.

>Maybe we should think of a smarter public API for it. Especially for removing drawables, which is required for a very common use case: pushing/popping clipping rectangles, as with a GUI. Speaking of GUIs, they will most likely want to define clipping masks from simple ```sf::FloatRect```s,

If we go with removing it from render states and instead setting it like a view. We could make the clipping mask heavier and maybe have it contain 2 vectors. One for drawables (so we can always have pixel custom shapes) and another vector for rects. When drawing the rects to the stencil buffer we could just generate the vertex data on the fly and then draw them.

**Comment by LaurentGomila** [comment]
> May I suggest however, lets focus on implementing it and not getting too nit picky

It's not about being nit picky, it's about finding the right API. Because once it's released, we can't go back before SFML 3. And you won't get so much feedback about this until it is released.

> I thought about caching the stencil buffer

Yes, I guess this could be done similar to what ```sf::RenderTarget``` already does for other render states.

> Just thinking here.... maybe instead of adding the clipping mask as part of the render states, we could make it like the view. With sf::RenderWindow::[set|get|clear]ClippingMask() so whenever the user changes the mask they must explicitly register it with the window.

Yes, I think these two options are the ones to consider. But they both have their drawbacks, so we should try to think about some typical use cases, and see how these solutions apply to them.

**Comment by zsbzsb** [comment]
>It's not about being nit picky, it's about finding the right API. Because once it's released, we can't go back before SFML 3. And you won't get so much feedback about this until it is released.

I guess it is an infinite loop then over never releasing stuff. This is what I am hoping to avoid.

No feedback? Don't implement. Not implemented? No feedback.

>Yes, I guess this could be done similar to what ```sf::RenderTarget``` already does for other render states.

As I said before, trouble with this is determining if the mask has changed since a subsequent draw call. The drawables don't implement a notify changed event or anything like that. This would be solved if we did it explicitly like the view.

**Component of RenderStates**
- Easy to change per draw call
- More inline with the current API design (blendmodes, transforms, shaders, ect...)
- Much harder to implement efficient caching of the mask

**Treat as a View with [get|set|clear]ClippingMask(...)***
- More explicit API for changing the mask
- More inline with the View API that states to change the mask you must be explicit
- Much easier to implement efficient caching of the mask

The more I think about this, I think best way to go about it is by treating the mask like the view and having an explicit API.

**Comment by Mischa-Alff** [comment]
It would be nice to be able to choose your stencil function's behavior. (Equal, Not Equal, Greater Than, Less Than, Always, Never...).

What's the reasoning behind `const Drawable*& operator [](std::size_t index);`? Why not just return a reference?

Also I don't think there should be an `operator[]` at all. It's not a simple list of shapes (like `VertexArray` is a list of vertexes). Perhaps a `getDrawables()` function or similar would be better.

(I haven't read through all the code, I just quickly glanced over it, so this whole thing might be void)
And, although I'm sure this has already been said, it appears that the mask is re-rendered at every draw call. This could be extremely slow and should be cached. I'm not sure if this is available in OpenGL 2.0, but you can render to a rendertexture and attach that texture to `GL_STENCIL_ATTACHMENT`, and only re-render it when the user calls an update function on the mask.

**Comment by zsbzsb** [comment]
>It would be nice to be able to choose your stencil function's behavior. (Equal, Not Equal, Greater Than, Less Than, Always, Never...).

What would be the advantage to this? I don't really see how this would help, the behavior is also determined by the 2nd and 3rd parameters which determine when the stencil buffer will be written. I'm not seeing anyway this could be useful besides exposing the implementation details.

>What's the reasoning behind ```const Drawable*& operator [](std::size_t index);```? Why not just return a reference?

I do believe that was a mistake that slipped in, I will check it.

>Also I don't think there should be an ```operator[]``` at all. It's not a simple list of shapes

Is it not supposed to be a simple list of drawables? :confused: 

>Perhaps a ```getDrawables()``` function or similar would be better.

And what would be that return type?

>it appears that the mask is re-rendered at every draw call. This could be extremely slow and should be cached.

Yes, read above - to do caching I am going to first change the API to behave like a view (see above comments).

>you can render to a rendertexture and attach that texture to ```GL_STENCIL_ATTACHMENT```, and only re-render it when the user calls an update function on the mask.

AFAIK ```GL_STENCIL_ATTACHMENT``` was added with FBOs in OpenGL 3.3. If you check the FBO render texture implementation, this is how I added a stencil buffer to the render texture FBO implementation. Also, how would rendering to a seperate render texture be any more efficient than using the stencil buffer included with the current target?

>Perhaps two clip modes could be implemented? One for a single rectangle (using glScissor), and one for complex geometry using the current implementation?

That is a good idea, so if we go with the ```RenderWindow::[set|get|clear]ClippingMask(...)``` we could also add ```RenderWindow::[set[get|clear]ClippingArea(...)``` which would use ```glScissors``` implementation. That way we can make both parties happy. The people that need GUI clipping get fast single rect clipping, and the people that need custom pixel based masks also get support.

**Comment by zsbzsb** [comment]
I just updated the API. I removed the clipping mask from the render states and instead added function the render target class for setting the mask.

There was a total of 6 functions added to the render target class.

```clearClipping[Area|Mask]();
setClipping[Area|Mask](...);
getClipping[Area|Mask]();```

Masks are the same as the previous comments, basically a list of drawables that allow users to define custom shapes / pixel based masks.

Areas on the other hand are limited to a single IntRect that is defined in window coordinates. The clipping area is implemented using ```glScissor(...)``` which should provide faster, simpler clipping for those who just need it for basic GUIs.

The clipping mask on the other hand is heavier and uses the stencil buffer for clipping. It works in scene coordinates and is used for more complex masks.

Both clipping modes are applied like the view is. To set a clipping mode you first call ```setClippingXXX(...)``` with the appropriate parameters. The clipping mode will be cached until it is either cleared or updated (another set call).

Below is some testing code to try it out.

```
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window({ 800, 600 }, "Clipping Mask Test");
    window.setVerticalSyncEnabled(true);

    // create a circle for part of the clipping mask
    sf::CircleShape keyholetop(50);
    keyholetop.setOrigin({ 50, 50 });

    // create a square for part of the clipping mask
    sf::RectangleShape keyholebody({ 36, 150 });
    keyholebody.setOrigin({ 18, 0 });

    // create the clipping mask
    sf::ClippingMask clipmask;

    // add the shapes to the clipping mask
    // sf::ClippingMask behaves like sf::VertexArray
    // so you can append any sf::Drawable to the mask
    // the mask will not copy the sf::Drawable, it only stores a pointer
    clipmask.append(keyholetop);
    clipmask.append(keyholebody);

    sf::Texture background;
    // use any background image
    // I used the image from opengl example
    background.loadFromFile("sfml/examples/opengl/resources/background.jpg");

    sf::Sprite backgroundsprite(background);

    // set a clipping area
    // for this example exlude the area 50px from the borders
    window.setClippingArea({ 50, 50, 700, 500 });

    while (window.isOpen())
    {
        sf::Event e;
        while (window.pollEvent(e))
        {
            if (e.type == sf::Event::Closed)
                window.close();
        }

        // get mouse position
        sf::Vector2f mousepos = window.mapPixelToCoords(sf::Mouse::getPosition(window));

        // update the mask position
        clipmask.setPosition(mousepos);

        //assign the clipping mask to the window
        window.setClippingMask(clipmask);

        window.clear(sf::Color::Blue);

        window.draw(backgroundsprite);

        window.display();
    }
}
```

**Comment by zsbzsb** [comment]
I will be creating a new PR because the original was based on gl_dev and well.... 2 years later nothing
https://github.com/isaacs/github/issues/18

**Pull request closed without merging**
