### PR TITLE
Added export to Joystick::Identification

### PR DESCRIPTION
**Pull request by mantognini**
Proper fix for #809.

NB: just testing the web based editor to branch/edit/PR... seems to be working nicely!

### CODE REVIEW

**Comment by binary1248** [comment]
Since this is such a trivial change... :+1:

Let's see how long the merge takes :stuck_out_tongue:.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by eXpl0it3r** [comment]
@binary1248 ~4h and even with a "non-standard" branch name... :wink:

**Comment by binary1248** [comment]
+points for being able to cope with the branch name... I wouldn't have been able to get that done in so little time given the circumstances :satisfied:.

**Comment by MarioLiebisch** [comment]
Yeah, that's lame, think of all the other branches that got tidy and use a clean branch name. They have to wait in line while the rowdy rushes through. :P

**Comment by mantognini** [comment]
If the name was standard there would not have been any challenge! :stuck_out_tongue_winking_eye:

**Pull request merged**
