### PR TITLE
Fixed missing pthread dependency

### PR DESCRIPTION
**Pull request by nullEuro**
The find script fails to add pthread to the SFML_SYSTEM_DEPENDENCIES when linking SFML statically on Linux.

### CODE REVIEW

**Comment by LaurentGomila** [comment]
Good catch.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Comment by binary1248** [comment]
:+1:

**Comment by eXpl0it3r** [comment]
Merged in 66f38262f71bc1d9f4c6e2731798e45a17e85efa

**Pull request closed without merging**
