### PR TITLE
Updated copyright year and Laurent's email address

### PR DESCRIPTION
**Pull request by zsbzsb**
Needs to be done at some point... better late than never. xD

I think I got all of them :smile:

### CODE REVIEW

**Comment by LaurentGomila** [comment]
I'm not going to check, I trust you :p

**Comment by mantognini** [comment]
Close but a few are missing. Look for .m, .mm and .plist files (might be more but that's the one I found). ;)

**Comment by zsbzsb** [comment]
>I'm not going to check, I trust you :p

Well @Bromeon missed some during the 2014 update :P

>Close but a few are missing. Look for .m, .mm and .plist files (might be more but that's the one I found). ;)

Done.

**Comment by mantognini** [comment]
I think your regex doesn't work with plist files in tools/xcode. The format is a bit different there. ;)

**Comment by zsbzsb** [comment]
>I think your regex doesn't work with plist files in tools/xcode. The format is a bit different there. ;)

What do you mean? The changes in those files look just fine to me.

**Comment by mantognini** [comment]
You're right. I thought you haven't changed those because they are not listed on the *Files Changed* tab.. Anyway, thanks!

**Comment by zsbzsb** [comment]
Github :stuck_out_tongue: 

>Sorry, we could not display the entire diff because too many files (305) changed.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.

**Pull request merged**
